"""fix slug video

Revision ID: 0392f232f25b
Revises: 5a08edf1cd56
Create Date: 2025-09-05 00:18:51.757579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0392f232f25b'
down_revision: Union[str, Sequence[str], None] = '5a08edf1cd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_video_slug'), 'video', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_slug'), table_name='video')
    # ### end Alembic commands ###
