"""update createAt movie user

Revision ID: 26772eeafe23
Revises: 870a1ff9bd36
Create Date: 2025-08-20 08:27:16.543674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision: str = '26772eeafe23'
down_revision: Union[str, Sequence[str], None] = '870a1ff9bd36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('createAt', sa.DateTime(), nullable=False, server_default=sa.text(f"'{datetime.datetime.now().isoformat(sep=' ', timespec='seconds')}'")))
    op.add_column('user', sa.Column('createAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'createAt')
    op.drop_column('movie', 'createAt')
    # ### end Alembic commands ###
