"""update movie model: poster thumbnail

Revision ID: 4c7ab010fc10
Revises: 26772eeafe23
Create Date: 2025-08-23 22:12:21.156034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4c7ab010fc10'
down_revision: Union[str, Sequence[str], None] = '26772eeafe23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_movie_slug'), 'movie', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_slug'), table_name='movie')
    op.alter_column('movie', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('movie', 'slug')
    op.drop_column('movie', 'poster')
    # ### end Alembic commands ###
