"""update carousel model link to movie

Revision ID: 62a4199acf68
Revises: 4c7ab010fc10
Create Date: 2025-08-24 18:18:19.162565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62a4199acf68'
down_revision: Union[str, Sequence[str], None] = '4c7ab010fc10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carousel', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('carousel', sa.Column('createAt', sa.DateTime(), nullable=False))
    op.drop_column('carousel', 'order')
    op.alter_column('movie', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'thumbnail',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('carousel', sa.Column('order', sa.INTEGER(), nullable=False))
    op.drop_column('carousel', 'createAt')
    op.drop_column('carousel', 'is_active')
    # ### end Alembic commands ###
