"""update video sub movie relation

Revision ID: 808e53933b8a
Revises: 754712e2a76e
Create Date: 2025-09-01 15:43:35.510500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '808e53933b8a'
down_revision: Union[str, Sequence[str], None] = '754712e2a76e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createAt', sa.DateTime(), nullable=False),
    sa.Column('movieId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieId'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('movie', 'linkSub')
    op.drop_column('movie', 'linkVideo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('linkVideo', sa.VARCHAR(), nullable=True))
    op.add_column('movie', sa.Column('linkSub', sa.VARCHAR(), nullable=True))
    op.drop_table('video')
    op.drop_table('sub')
    # ### end Alembic commands ###
