"""update movie category

Revision ID: d6049884c420
Revises: 77c4df495319
Create Date: 2025-08-28 00:22:59.248541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6049884c420'
down_revision: Union[str, Sequence[str], None] = '77c4df495319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'category',
        sa.Column('isDisplay', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.drop_column('category', 'isActive')
    op.add_column('movie', sa.Column('fact', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'fact')
    op.add_column('category', sa.Column('isActive', sa.BOOLEAN(), nullable=False))
    op.drop_column('category', 'isDisplay')
    # ### end Alembic commands ###
