"""update movie trailer

Revision ID: eea0a8a02d0d
Revises: 808e53933b8a
Create Date: 2025-09-01 16:09:21.666655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eea0a8a02d0d'
down_revision: Union[str, Sequence[str], None] = '808e53933b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('trailer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'trailer')
    # ### end Alembic commands ###
